// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1LDPDP9GAzfQuaZvtt0adLBRMY-BJ0PU',
    appId: '1:198457724156:web:16505799a62867be3a9b79',
    messagingSenderId: '198457724156',
    projectId: 'find-missing-children',
    authDomain: 'find-missing-children.firebaseapp.com',
    storageBucket: 'find-missing-children.appspot.com',
    measurementId: 'G-78MPNQ8PCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUdvc2pTq3597X87Lll0sSXDozTe8QgMU',
    appId: '1:198457724156:android:c235a9e09dbef3ab3a9b79',
    messagingSenderId: '198457724156',
    projectId: 'find-missing-children',
    storageBucket: 'find-missing-children.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKuO2d3w0VALLLWhslleU3W31lA4aoCwk',
    appId: '1:198457724156:ios:efdb1d7114d993e63a9b79',
    messagingSenderId: '198457724156',
    projectId: 'find-missing-children',
    storageBucket: 'find-missing-children.appspot.com',
    iosBundleId: 'com.example.findMissingTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKuO2d3w0VALLLWhslleU3W31lA4aoCwk',
    appId: '1:198457724156:ios:10982817b90f230a3a9b79',
    messagingSenderId: '198457724156',
    projectId: 'find-missing-children',
    storageBucket: 'find-missing-children.appspot.com',
    iosBundleId: 'com.example.findMissingTest.RunnerTests',
  );
}
